import uuid from 'react-native-uuid';

export const PANTRIES = [
	{
		id: uuid.v4(),
		name: 'Grocery list',
		creationDate: Date.now(),
		modifyDate: Date.now(),
		inventory: [
			{
				id: 'dietPepsi',
				name: 'Diet Pepsi',
				qty: '24 pack',
				staple: true,
				needed: true,
				listed: true,
				images: [],
				price: '7.99',
				loc: 'HEB aisle 20',
				url: '',
				upc: '',
				purchaseBy: 0,
				interval: 0,
				history: [],
				notes: '',
				creationDate: Date.now(),
				modifyDate: Date.now()
			},
			{
				id: 'sourdoughPretzels',
				name: 'Sourdough pretzels',
				qty: '1',
				staple: false,
				needed: true,
				listed: true,
				images: [],
				price: '3.49',
				loc: 'HEB snack aisle',
				url: '',
				upc: '',
				purchaseBy: 0,
				interval: 0,
				history: [],
				notes: '',
				creationDate: Date.now(),
				modifyDate: Date.now(),
			},
			{
				id: 'wholeWheatBread',
				name: 'Whole-wheat bread',
				qty: '1',
				staple: true,
				needed: true,
				listed: true,
				images: [],
				price: '1.99',
				loc: 'HEB bakery',
				url: '',
				upc: '',
				purchaseBy: 0,
				interval: 0,
				history: [],
				notes: '',
				creationDate: Date.now(),
				modifyDate: Date.now(),
			},
			{
				id: 'tofu',
				name: 'Tofu',
				qty: '1',
				staple: false,
				needed: false,
				listed: true,
				images: [],
				price: '2.99',
				loc: 'Walmart cold case',
				url: '',
				upc: '',
				purchaseBy: 0,
				interval: 0,
				history: [],
				notes: '',
				creationDate: Date.now(),
				modifyDate: Date.now(),
			}
		]
	},
	{
		id: uuid.v4(),
		name: 'Hardware store',
		creationDate: Date.now(),
		modifyDate: Date.now(),
		inventory: [
			{
				id: 'plywood',
				name: 'Plywood',
				qty: '1',
				staple: false,
				needed: true,
				listed: true,
				images: [],
				price: '',
				loc: '',
				url: '',
				upc: '',
				purchaseBy: 0,
				interval: 0,
				history: [],
				notes: 'Birch',
				creationDate: Date.now(),
				modifyDate: Date.now()
			},
			{
				id: 'pruningShears',
				name: 'Pruning shears',
				qty: '1',
				staple: false,
				needed: true,
				listed: true,
				images: [],
				price: '',
				loc: '',
				url: '',
				upc: '',
				purchaseBy: 0,
				interval: 0,
				history: [],
				notes: 'left-handed',
				creationDate: Date.now(),
				modifyDate: Date.now()
			},
			{
				id: 'aaaBatteries',
				name: 'AAA batteries',
				qty: '8 pk',
				staple: false,
				needed: true,
				listed: true,
				images: [],
				price: '',
				loc: '',
				url: '',
				upc: '',
				purchaseBy: 0,
				interval: 0,
				history: [],
				notes: '',
				creationDate: Date.now(),
				modifyDate: Date.now()
			},
			{
				id: 'groutCleaner',
				name: 'Grout cleaner',
				qty: '1',
				staple: false,
				needed: false,
				listed: false,
				images: [],
				price: '',
				loc: '',
				url: '',
				upc: '',
				purchaseBy: 0,
				interval: 0,
				history: [],
				notes: '',
				creationDate: Date.now(),
				modifyDate: Date.now()
			}
		]
	}
]
